CREATE DATABASE lv_safety_verification;
use lv_safety_verification;


--------> Site Table <------------

CREATE TABLE site_table (
		    SITE_ID INT AUTO_INCREMENT,
			SITE_CODE VARCHAR(255) NOT NULL,
		    USER_NAME VARCHAR(255),
			SITE VARCHAR(255) NOT NULL,
			COMPANY_NAME VARCHAR(255) NOT NULL,
			DEPARTMENT_NAME VARCHAR(255) NOT NULL,
			ADDRESSLINE_1 VARCHAR(255) NOT NULL,
			ADDRESSLINE_2 VARCHAR(255) NULL,
			LAND_MARK VARCHAR(255) NULL,
			CITY VARCHAR(255) NULL,
			STATE VARCHAR(255) NOT NULL,
			COUNTRY VARCHAR(255) NOT NULL,
			ZIP_CODE VARCHAR(255) NOT NULL,
			ALL_STEPS_COMPLETED VARCHAR(255),
			SITE_ASSIGNED_TO VARCHAR(255) NOT NULL,
			STATUS VARCHAR(50),		    		
			CREATED_BY VARCHAR(255) NOT NULL,
		    UPDATED_BY VARCHAR(255) NOT NULL,
		    CREATED_DATE datetime NOT NULL,    
		    UPDATED_DATE datetime NOT NULL,
			CONSTRAINT PK_SITE_ID PRIMARY KEY(SITE_ID)
);

CREATE TABLE site_person_table(
			 PERSON_ID INT AUTO_INCREMENT,
			 SITE_NAME VARCHAR(255),
			 SITE_ID INT,
			 IN_ACTIVE BIT,
			 PERSON_INCHARGE VARCHAR(255),
			 E_mail VARCHAR(255) NOT NULL,
			 DESIGNATION VARCHAR(255),
			 CONTACT_NO VARCHAR(255),
			 CONSTRAINT PK_PERSON_ID PRIMARY KEY(PERSON_ID),
			 CONSTRAINT FK_SITE_ID FOREIGN KEY (SITE_ID) REFERENCES site_table(SITE_ID) ON DELETE CASCADE
 );



--------> Part_1  Basic information


CREATE TABLE report_details_table (
		    REPORT_ID INT AUTO_INCREMENT,
		    SITE_ID INT,
			USER_NAME VARCHAR(255),
			DESCRIPTION_REPORT VARCHAR(500),
			REASON_REPORT VARCHAR(500),
			INSTALLATION_TYPE VARCHAR(255),
			DESCRIPTION_PREMISE VARCHAR(255) ,
			ESTIMATED_WIRE_AGE VARCHAR(255),
			EVIDANCE_ADDITION VARCHAR(255),
			EVIDANCE_WIRE_AGE VARCHAR(255),
		    PREVIOUS_RECORDS VARCHAR(255),
		    LAST_INSPECTION VARCHAR(255),
		    NEXT_INSPECTION VARCHAR(255),	
		    EXTENT_INSTALLATION VARCHAR(500),
		    CLIENT_DETAILS VARCHAR(500),
		    INSTALLATION_DETAILS VARCHAR(500),
		    VERIFICATION_DATE VARCHAR(500),  
		    VERIFIED_ENGINEER VARCHAR(255),
		    DESIGNATION VARCHAR(255) ,
		    COMPANY VARCHAR(255),
		    INSPECTOR_DESIGNATION VARCHAR(255),
		    INSPECTOR_COMPANYNAME VARCHAR(255),
		    LIMITATIONS VARCHAR(255),
			CREATED_BY VARCHAR(255),
		    CREATED_DATE datetime,
		    UPDATED_BY VARCHAR(255),
            UPDATED_DATE datetime,
		    CONSTRAINT PK_REPORT_ID PRIMARY KEY(REPORT_ID)
 );
 
 CREATE TABLE sign_details_table (
            SIGNATOR_ID INT AUTO_INCREMENT,
            REPORT_ID INT,
			SIGNATOR_ROLE VARCHAR(255),
			PERSON_NAME VARCHAR(255),
			PERSON_CONTACT_NO VARCHAR(255),
			PERSON_MAIL_ID VARCHAR(255),
			MANAGER_NAME VARCHAR(255),
			MANAGER_CONTACT_NO VARCHAR(255),
			MANAGER_MAIL_ID VARCHAR(255),
			COMPANY_NAME VARCHAR(255),
			ADDRESS_LINE1 VARCHAR(255),
			ADDRESS_LINE2 VARCHAR(255),
			LAND_MARK VARCHAR(255),
			STATE VARCHAR(255),
			PIN_CODE VARCHAR(255),
			COUNTRY VARCHAR(255),
			DECLARATION_DATE VARCHAR(255),
			DECLARATION_NAME VARCHAR(255),
			DECLARATION_SIGNATURE LONGTEXT,
			SIGNATOR_STATUS VARCHAR(20),
			CONSTRAINT PK_SIGNATOR_ID PRIMARY KEY(SIGNATOR_ID),
			CONSTRAINT FK_REPORT_ID FOREIGN KEY (REPORT_ID) REFERENCES report_details_table(REPORT_ID) ON DELETE CASCADE
);
 
CREATE TABLE reportdetails_comments_table(

		   COMMENTS_ID INT AUTO_INCREMENT,
		   REPORT_ID INT,
		   VIEWER_USERNAME VARCHAR(225),
		   INSPECTOR_USERNAME VARCHAR(225),
		   VIEWER_EMAIL VARCHAR(225),
		   INSPECTOR_EMAIL VARCHAR(225),
		   SITE_NAME VARCHAR(225),
		   VIEWER_COMMENT VARCHAR(500),
		   VIEWER_UPDATEDATE VARCHAR(225),
		   INSPECTOR_COMMENT VARCHAR(500),
           INSPECTOR_UPDATEDATE VARCHAR(225),		
           COMMENT_APPROVE_OR_REJECT VARCHAR(225),
           VIEWER_FLAG VARCHAR(225),
           INSPECTOR_FLAG VARCHAR(225),
           NO_OF_COMMENT INT,
		   CONSTRAINT PK_COMMENTS_ID PRIMARY KEY(COMMENTS_ID),
		   CONSTRAINT FK_COMMENTS_REPORT_ID FOREIGN KEY (REPORT_ID) REFERENCES report_details_table(REPORT_ID) ON DELETE CASCADE

);
 



--------> Part_2 Supply characteristics and earthing arrangement API.

CREATE TABLE supply_characteristics_table (

            SUPPLY_CHARACTERISTICS_ID INT AUTO_INCREMENT,
			SITE_ID INT,
			USER_NAME VARCHAR(255),
            SHORT_NAME VARCHAR(255),
            MAIN_SYSTEM_EARTING VARCHAR(255),
            SYSTEM_EARTH_BNOTE VARCHAR(255),
            LIVE_CONDUCTOR_TYPE VARCHAR(255),
            LIVE_CONDUCTOR_AC VARCHAR(255),
            LIVE_CONDUCTOR_DC VARCHAR(255),
            LIVE_CONDUCTOR_BNOTE VARCHAR(255),
            MAIN_NOMINAL_CAPACITY VARCHAR(255),
            MAIN_ACTUALLOAD VARCHAR(255),
            MAIN_NOMINAL_VOLTAGE VARCHAR(255),
            MAIN_NOMINAL_FREQUENCY VARCHAR(255),
            MAIN_FAULT_CURRENT VARCHAR(255),
            MAIN_LOOP_IMPEDANCE VARCHAR(255),
            MAIN_CURRENT_PROTECTIVE_DEVICE VARCHAR(255),
            MAIN_RATED_CURRENT VARCHAR(255),
            MAIN_CURRENT_DISCONNECTION VARCHAR(255),
            AL_AVILABLE_SUPPLY VARCHAR(255),
            AL_NUM_SUPPLY VARCHAR(255),
            MAXIMUM_DEMAND VARCHAR(255),
            MAXIMUM_LOAD VARCHAR(255),
            MEANS_EARTHING VARCHAR(255),
            EARTHING_REMARKS VARCHAR(255),
            ELECTORDE_TYPE VARCHAR(255),
            ELECTORDE_MATERIAL VARCHAR(255),
            NUM_LOCATION INT,
            CONDUCTOR_SIZE VARCHAR(255),
            CONDUCTOR_MATERIAL VARCHAR(255),
            CONDUCTOR_VERIFY VARCHAR(255),
            BONDING_CONDUCTOR_SIZE VARCHAR(255),
            BONDING_CONDUCTOR_MATERIAL VARCHAR(255),
            BONDING_CONDUCTOR_VERIFY VARCHAR(255),
            BONDING_JOINTS_TYPE VARCHAR(255),
            BONDING_NO_OF_JOINTS INT,
            EARTHING_CONDUCTOR_SIZE VARCHAR(255),
            EARTHING_CONDUCTOR_MATERIAL VARCHAR(255),
            EARTHING_CONDUCTOR_VERIFY VARCHAR(255),
            EARTHING_JOINTS_TYPE VARCHAR(255),
            EARTHING_NO_OF_JOINTS INT,
            EARTHING_NO_OF_JOINTS_OB  VARCHAR(500),
            BONDING_NO_OF_JOINTS_OB  VARCHAR(500),
            INSTALLOCATION_REPORT_OB  VARCHAR(500),
            CREATED_BY VARCHAR(255),
		    CREATED_DATE datetime,
		    UPDATED_BY VARCHAR(255),
            UPDATED_DATE datetime,
            CONSTRAINT PK_SUPPLY_CHARACTERISTICS_ID PRIMARY KEY(SUPPLY_CHARACTERISTICS_ID)
              
);
 
CREATE TABLE supply_parameters_table (

            SUPPLY_PARAMETERS_ID INT AUTO_INCREMENT,
            SUPPLY_CHARACTERISTICS_ID INT,
            AL_SYSTEM_EARTING VARCHAR(255),
            AL_SUPPLY_NO VARCHAR(255),
            AL_SUPPLY_STNAME VARCHAR(255),
            AL_SYSTEM_EARTING_BNOTE VARCHAR(255),
            AL_LIVECONDUCTOR_TYPE VARCHAR(255),
            AL_LIVECONDUCTOR_AC VARCHAR(255),
            AL_LIVECONDUCTOR_DC VARCHAR(255),
            AL_LIVECONDUCTOR_BNOTE VARCHAR(255),
             AL_NOMINAL_VOLTAGE VARCHAR(255),
            AL_NOMINAL_FREQUENCY VARCHAR(255),
            AL_FAULT_CURRENT VARCHAR(255),
            AL_LOOP_IMPEDANCE VARCHAR(255),
            AL_INSTALLED_CAPACITY VARCHAR(255),
            AL_ACTUAL_LOAD VARCHAR(255) ,
            AL_PROTECTIVE_DEVICE VARCHAR(255),
            AL_RATED_CURRNT VARCHAR(255),
            AL_CURRENT_DISCONNECTION VARCHAR(255),
            SUPPLY_PARAMETER_STATUS VARCHAR(255),
            CONSTRAINT PK_SUPPLY_PARAMETERS_ID PRIMARY KEY(SUPPLY_PARAMETERS_ID),
            CONSTRAINT FK_SUPPLY_CHARACTERISTICS_ID FOREIGN KEY (SUPPLY_CHARACTERISTICS_ID) REFERENCES supply_characteristics_table(SUPPLY_CHARACTERISTICS_ID) ON DELETE CASCADE

 );
 
  CREATE TABLE circuit_breaker_table (
 
            CIRCUIT_BREAKER_ID INT AUTO_INCREMENT, 
            SUPPLY_CHARACTERISTICS_ID INT,
            LOCATION VARCHAR(255),
            SOURCE_NAME VARCHAR(255),
            MAKE VARCHAR(255),
            CURRENT_CURVE VARCHAR(255),
            TYPE VARCHAR(255),
            POLES_NO VARCHAR(255),
            CURRRENT VARCHAR(255),
            VOLTAGE VARCHAR(255),
            FUSE VARCHAR(255),
            TYPE_OF_RESIDUALCURRENT  VARCHAR(255),
            RESIDUAL_CURRENT VARCHAR(255),
            RESIDUAL_TIME VARCHAR(255),
            CIRCUIT_STATUS VARCHAR(255),
            CONSTRAINT PK_CIRCUIT_BREAKER_ID PRIMARY KEY(CIRCUIT_BREAKER_ID),
            CONSTRAINT FK_CIRCUIT_BREAKER_SUPPLY_CHARACTERISTICS_ID FOREIGN KEY (SUPPLY_CHARACTERISTICS_ID) REFERENCES supply_characteristics_table(SUPPLY_CHARACTERISTICS_ID) ON DELETE CASCADE
                   
);

CREATE TABLE installation_location_table (
            INSTALLATION_LOCATION_REPORT_ID INT AUTO_INCREMENT,
            SUPPLY_CHARACTERISTICS_ID INT,
            LOCATION_NO VARCHAR(255),
            LOCATION_NAME VARCHAR(500),
            MEANS_EARTHING_REMARK VARCHAR(500),
            ELECTRODE_EARTH_TYPE VARCHAR(255),
            ELECTRODE_EARTH_MATERIAL VARCHAR(255),
            ELECTRODE_EARTH_DEPTH VARCHAR(255),
            ELECTRODE_EARTH_SIZE VARCHAR(255),
            ELECTORDE_RESISTANCE_EARTH VARCHAR(500),
            ELECTORDE_RESISTANCE_GRID VARCHAR(255),
            INSTALLOCATIONREPORT_STATUS VARCHAR(255),
            CONSTRAINT PK_INSTALLATION_LOCATION_REPORT_ID PRIMARY KEY(INSTALLATION_LOCATION_REPORT_ID),
            CONSTRAINT FK_INSTALLATION_LOCATION_REPORTS_SUPPLY_CHARACTERISTICS_ID FOREIGN KEY (SUPPLY_CHARACTERISTICS_ID) REFERENCES supply_characteristics_table(SUPPLY_CHARACTERISTICS_ID) ON DELETE CASCADE


 );

 CREATE TABLE bounding_location_reports_table (
            BOUNDING_REPORT_ID INT AUTO_INCREMENT,
            SUPPLY_CHARACTERISTICS_ID INT,
			LOCATION VARCHAR(255),
			JOINT_NO VARCHAR(255),
			JOINT_REFERENCE VARCHAR(255),
            JOINT_RESISTANCE VARCHAR(255) ,
            INSTALLOCATIONREPORT_STATUS VARCHAR(255),
            CONSTRAINT PK_BOUNDING_LOCATION_REPORT_ID PRIMARY KEY(BOUNDING_REPORT_ID),
            CONSTRAINT FK_BOUNDING_LOCATION_REPORTS_SUPPLY_CHARACTERISTICS_ID FOREIGN KEY (SUPPLY_CHARACTERISTICS_ID) REFERENCES supply_characteristics_table(SUPPLY_CHARACTERISTICS_ID) ON DELETE CASCADE


 );
 
  CREATE TABLE earthing_location_reports_table (
            EARTHING_LOCATION_REPORT_ID INT AUTO_INCREMENT,
            SUPPLY_CHARACTERISTICS_ID INT,
			LOCATION VARCHAR(255),
			JOINT_NO VARCHAR(255),
			JOINT_REFERENCE VARCHAR(255),
            JOINT_RESISTANCE VARCHAR(255) ,
            INSTALLOCATIONREPORT_STATUS VARCHAR(255),
            CONSTRAINT PK_EARTHING_LOCATION_REPORT_ID PRIMARY KEY(EARTHING_LOCATION_REPORT_ID),
            CONSTRAINT FK_EARTHING_LOCATION_REPORTS_SUPPLY_CHARACTERISTICS_ID FOREIGN KEY (SUPPLY_CHARACTERISTICS_ID) REFERENCES supply_characteristics_table(SUPPLY_CHARACTERISTICS_ID) ON DELETE CASCADE


 );
 
CREATE TABLE supplycharacteristic_comments_table(

		   COMMENTS_ID INT AUTO_INCREMENT,
		   SUPPLY_CHARACTERISTICS_ID INT,
		   VIEWER_USERNAME VARCHAR(225),
		   INSPECTOR_USERNAME VARCHAR(225),
		   VIEWER_EMAIL VARCHAR(225),
		   INSPECTOR_EMAIL VARCHAR(225),
		   SITE_NAME VARCHAR(225),
		   VIEWER_COMMENT VARCHAR(500),
		   VIEWER_UPDATEDATE VARCHAR(225),
		   INSPECTOR_COMMENT VARCHAR(500),
           INSPECTOR_UPDATEDATE VARCHAR(225),		
           COMMENT_APPROVE_OR_REJECT VARCHAR(225),
           VIEWER_FLAG VARCHAR(225),
           INSPECTOR_FLAG VARCHAR(225),
           NO_OF_COMMENT INT,
		   CONSTRAINT PK_COMMENTS_ID PRIMARY KEY(COMMENTS_ID),
           CONSTRAINT FK_COMMENTS_SUPPLY_CHARACTERISTICS_ID FOREIGN KEY (SUPPLY_CHARACTERISTICS_ID) REFERENCES supply_characteristics_table(SUPPLY_CHARACTERISTICS_ID) ON DELETE CASCADE

);

CREATE TABLE supply_outer_observation_table(

		   SUPPLY_OUTER_OBSERVATION_ID INT AUTO_INCREMENT,
		   SUPPLY_CHARACTERISTICS_ID INT,
		   OBSERVATION_COMPONENT_DETAILS VARCHAR(225),
		   OBSERVATION_DESCRIPTION VARCHAR(500),
		   SUPPLY_OUTER_OBSERVATION_STATUS VARCHAR(225),
		   CONSTRAINT PK_SUPPLY_OUTER_OBSERVATION_ID PRIMARY KEY(SUPPLY_OUTER_OBSERVATION_ID),
           CONSTRAINT FK_OBSERVATION_SUPPLY_CHARACTERISTICS_ID FOREIGN KEY (SUPPLY_CHARACTERISTICS_ID) REFERENCES supply_characteristics_table(SUPPLY_CHARACTERISTICS_ID) ON DELETE CASCADE

);

CREATE TABLE supply_alternative_inner_observations_table(

		   SUPPLY_INNER_OBSERVATIONS_ID INT AUTO_INCREMENT,
		   SUPPLY_OUTER_OBSERVATION_ID INT,
		   OBSERVATION_COMPONENT_DETAILS VARCHAR(225),
		   OBSERVATION_DESCRIPTION VARCHAR(500),
		   ALTERNATIVE_INNER_OBSERVATION_STATUS VARCHAR(225),
		   CONSTRAINT PK_SUPPLY_INNER_OBSERVATIONS_ID PRIMARY KEY(SUPPLY_INNER_OBSERVATIONS_ID),
           CONSTRAINT FK_SUPPLY_OUTER_OBSERVATION_ID  FOREIGN KEY (SUPPLY_OUTER_OBSERVATION_ID) REFERENCES supply_outer_observation_table(SUPPLY_OUTER_OBSERVATION_ID) ON DELETE CASCADE

);
 
 
--------> part_3  Periodic_inspection
CREATE TABLE periodic_inspection_table(

            PERIODIC_INSPECTION_ID INT AUTO_INCREMENT,
            SITE_ID INT,
			USER_NAME VARCHAR(225),
			CREATED_BY VARCHAR(255),
		    CREATED_DATE datetime,
		    UPDATED_BY VARCHAR(255),
            UPDATED_DATE datetime,
			CONSTRAINT PK_PERIODIC_INSPECTION_ID PRIMARY KEY(PERIODIC_INSPECTION_ID)

);
CREATE TABLE ipao_inspection_table (
            IPAO_INSPECTION_ID INT AUTO_INCREMENT,
            PERIODIC_INSPECTION_ID INT,
            LOCATION_NUMBER INT,
            LOCATION_NAME VARCHAR(225),
            I_SERVICE_CABLE VARCHAR(20),
            I_SERVICE_FUSE VARCHAR(20),
            ELECTRIC_SHOCK VARCHAR(255),
            BASIC_PROTECTION VARCHAR(255),
            FAULT_PROTECTION VARCHAR(255),
            LIMITED_VALUE VARCHAR(255),
            PROTECTIVE_MEASURE VARCHAR(255),
            ADDITIONAL_MEASURE VARCHAR(255),
            ADDITIONAL_PROTECTION VARCHAR(255),
            FAULT_PROTECTION_DESC VARCHAR(500),
            I_METER_DISTRIBUTOR VARCHAR(20),
            I_METER_CONSUMER VARCHAR(20),
            I_METER_EQU VARCHAR(20),
            I_TOV_MEASURES_LV_HV VARCHAR(20),
            I_ISOLATOR VARCHAR(20),
            P_EARTHING_ARRANGEMENT VARCHAR(20),
            P_ADEQUATE_ARRANGEMENT VARCHAR(20),
            P_CONNECTION_GENERATOR VARCHAR(20),
            P_COMPATIBILITY_CHARACTERISTICS VARCHAR(20),
            P_AUTOMATIC_DISCONNECT_GENERATOR VARCHAR(20),
            P_PREVENT_CONNECT_GENERATOR VARCHAR(20),
            P_ISOLATE_GENERATOR VARCHAR(20),
            A_MAIN_EARTHING VARCHAR(20),
            A_EARTH_ELECTORDE_ARRANGEMENT VARCHAR(20),
            A_EARTH_CONDUCTOR_CONNECTION VARCHAR(20),
            A_ACCESSIBILITY VARCHAR(20),
            A_MAIN_PROTECT_BONDING VARCHAR(20),
            A_ALL_PROTECT_BONDING VARCHAR(20),
            A_ALL_APPROPRIATE_LOCATION VARCHAR(20),
            A_FELV_REQUIREMENT VARCHAR(20),
            O_SELV_SYSTEM VARCHAR(20),
            O_PELV_SYSTEM VARCHAR(20),
            O_DOUBLE_INSULATION VARCHAR(20),
            O_REINFORCED_INSULATION VARCHAR(20),
            O_BASIC_ELECTRICAL_SEPARTION VARCHAR(20),
            O_ISOLATE_PUBLIC_SUPPLY VARCHAR(20),
            O_INSULATION_LIVE_PARTS VARCHAR(20),
            O_BARRIERS_ENCLOSERS VARCHAR(20),
            O_OBSTACLES VARCHAR(20),
            O_PLACING_OUT_REACH VARCHAR(20),
            O_FAULT_NON_CONDUCT_LOCATION VARCHAR(20),
            O_FAULT_ELECTRICAL_SEPARTION VARCHAR(20),
            O_OPERATING_CURRENT VARCHAR(20),
            O_SUPPLEMENTARY_BONDING VARCHAR(20),
            O_SPECIFIC_INSPECTION_RE VARCHAR(500),
            INSPECTION_FLAG VARCHAR(20),
 			LOCATION_COUNT INT NOT NULL,
            CONSTRAINT PK_IPAO_INSPECTION_ID PRIMARY KEY(IPAO_INSPECTION_ID),
            CONSTRAINT FK_PERIODIC_INSPECTION_ID  FOREIGN KEY (PERIODIC_INSPECTION_ID) REFERENCES periodic_inspection_table(PERIODIC_INSPECTION_ID) ON DELETE CASCADE
 );
 
 CREATE TABLE consumer_table (  
            CONSUMER_ID INT AUTO_INCREMENT,
	        IPAO_INSPECTION_ID INT,
            DISTRIBUTIONBOARD_DETAILS VARCHAR(225),
            REFERANCE VARCHAR(225),
            LOCATION VARCHAR(225),
            ACCESS_AND_WORKING VARCHAR(20),
            SECURITY_OF_FIXING VARCHAR(20),
            LIVE_PARTS_NOT_DAMAGE VARCHAR(20),
            SECURITY_OF_BARRIERS VARCHAR(20),
            SUITABILITY_OF_ENCLOSURE VARCHAR(20),
            ENCLOSURE_NOT_DAMAGED VARCHAR(20),
            PRESENCE_OF_OBSTACLES VARCHAR(20),
            PLACING_OUT_OF_CONSUMER VARCHAR(20),
            PRESENCE_MAIN_SWITCHES VARCHAR(20),
            OPERATION_MAIN_SWITCHES VARCHAR(20),
            MANUAL_CIRCUIT_BREAKERS VARCHAR(20),
            SWITCH_CAUSES_RCD VARCHAR(20),
            RCD_FAULT_PROTECTION VARCHAR(20),
            RCD_ADDITIONAL_PROTECTION VARCHAR(20),
            OVER_VOLTAGE_PROTECTION VARCHAR(20),
            INDICATION_OF_SPD VARCHAR(20),
            RCD_QUARTERLY_TEST VARCHAR(20),
            DIAGRAMS_CHARTS VARCHAR(20),
            NONSTANDARD_CABLE_COLOUR VARCHAR(20),
            AL_SUPPLY_OF_ORIGN VARCHAR(20),
            AL_SUPPLY_OF_METER VARCHAR(20),
            AL_SUPPLY_DISTRIBUTION VARCHAR(20),
            ALL_POINTS_ISOLATION VARCHAR(20),
            NEXT_INSPECTION VARCHAR(20),
            OTHER_REQUIRED_LABELLING VARCHAR(20),
            BASES_CORRECT_TYPE VARCHAR(20),
            SINGLE_POLE VARCHAR(20),
            MECHANICAL_DAMAGE VARCHAR(20),
            ELECTROMAGNETIC VARCHAR(20),
            ALL_CONDUCTOR_CON VARCHAR(20),
            CONSUMER_STATUS VARCHAR(20),
            LOCATION_COUNT INT NOT NULL,
			CONSTRAINT PK_CONSUMER_ID PRIMARY KEY(CONSUMER_ID),
			CONSTRAINT FK_CONSUMER_IPAO_INSPECTION_ID  FOREIGN KEY (IPAO_INSPECTION_ID) REFERENCES ipao_inspection_table(IPAO_INSPECTION_ID) ON DELETE CASCADE

 );
		
CREATE TABLE circuit_table (      
            CIRCUIT_ID INT AUTO_INCREMENT,
		    IPAO_INSPECTION_ID INT ,
		    DISTRIBUTIONBOARD_DETAILS VARCHAR(225),
            REFERANCE VARCHAR(225),
            LOCATION VARCHAR(225),
            IDENTIFICATION_CONDUCTORS VARCHAR(20),
            CABLE_INSTALLATION VARCHAR(20),
            EXAMINATION_CABLES VARCHAR(20),
            EXAMINATION_INSULATION VARCHAR(20),
            NON_SHEATHED_CABLES VARCHAR(20),
            CONTAINMENT_SYSTEMS VARCHAR(20),
            TEMPERATURE_RATING VARCHAR(20),
            CABLES_TERMINATED VARCHAR(20),
            CURRENT_CARRY_CAPACITY VARCHAR(20),
            ADEQUACY_PROTECT_DEVICES VARCHAR(20),
            PRESENCE_PROTECT_CONDUCTORS VARCHAR(20),
            CO_ORDINATION VARCHAR(20),
            WIRING_SYSTEMS VARCHAR(20),
            CABLES_CONCEAL_UNDER_FLOORS VARCHAR(20),
            OPERATING_CURRENT_CIRCUITS VARCHAR(20),
            OPERATING_CURRENT_SOCKET VARCHAR(20),
            CABLES_CONC_DEPTH VARCHAR(20),
            SECTIONS_REGARDLESS_DEPTH VARCHAR(20),
            PROVISION_FIRE_BARRIERS VARCHAR(20),
            SEPARATION_BAND VARCHAR(20),
            SEPARATION_ELECTRICAL VARCHAR(20),
            CONDITION_CIRCUIT_ACCESSORIES VARCHAR(20),
            CONDUCTOR_CORRECT_TERMINATED VARCHAR(20),
            CONDUCTOR_VISIBLE_OUTSIDE VARCHAR(20),
            CONN_LIVE_CONDUCTORS VARCHAR(20),
            ADEQUATELY_CONNECTED_ENCLOSURE VARCHAR(20),
            SUITABILITY_CIRCUIT_ACCESSORIES VARCHAR(20),
            CONDITION_ACCESSORIES VARCHAR(20),
            SINGLE_POLE_DEVICES VARCHAR(20),
            ADEQUACY_CONNECTIONS VARCHAR(20),
            ISOLATION_AND_SWITCHING VARCHAR(20),
            CIRCUIT_STATUS VARCHAR(20),
			CONSTRAINT PK_CIRCUIT_ID PRIMARY KEY(CIRCUIT_ID),
			CONSTRAINT FK_CIRCUIT_IPAO_INSPECTION_ID  FOREIGN KEY (IPAO_INSPECTION_ID) REFERENCES ipao_inspection_table(IPAO_INSPECTION_ID) ON DELETE CASCADE
);    
		
		                    
CREATE TABLE isolation_current_table (       
            ISOLATION_CURRENT_ID INT AUTO_INCREMENT,
	    	IPAO_INSPECTION_ID INT,
            I_PRESENCE_DEVICES VARCHAR(20),
            I_CONDITION_DEVICES VARCHAR(20),
            I_LOCATION_DEVICES VARCHAR(20),
            I_CAPABLE_SECURED VARCHAR(20),
            I_OPERATION_VERIFY VARCHAR(20),
            I_INSTALL_CIRCUIT VARCHAR(20),
            I_WARNING_LABEL VARCHAR(20),
            SW_PRESENCE_DEVICES VARCHAR(20),
            SW_CONDITION_DEVICES VARCHAR(20),
            SW_ACCEPTABLE_LOCATION VARCHAR(20),
            SW_CAPABLE_OFF_POSITION VARCHAR(20),
            SW_CORRECT_OPERATION VARCHAR(20),
            SW_CIRCUIT VARCHAR(20),
            SW_WARNING_LABEL VARCHAR(20),
            EM_SWIT_PRESENCE_DEVICES VARCHAR(20),
            EM_SWIT_CONDITION_DEVICES VARCHAR(20),
            EM_SWIT_LOCATION_DEVICES VARCHAR(20),
            EM_SWIT_OPERATION_VERIFY VARCHAR(20),
            EM_SWIT_INSTALL_CIRCUIT VARCHAR(20),
            FU_SWIT_PRESENCE_DEVICES VARCHAR(20),
            FU_SWIT_LOCATION_DEVICES VARCHAR(20),
            FU_SWIT_OPERATION_VERIFY VARCHAR(20),
            C_SUITABILITY_EQUIPMENT VARCHAR(20),
            C_ENCLOSURE_NOT_DAMAGED VARCHAR(20),
            C_SUITABILITY_ENVIRONMENT VARCHAR(20),
            C_SECURITY_FIXING VARCHAR(20),
            C_CABLE_ENTRY_HOLES VARCHAR(20),
            C_PROVISION_VOLTAGE VARCHAR(20),
            C_PROVISION_OVERLOAD VARCHAR(20),
            C_CORRECT_TYPE_LAMPS VARCHAR(20),
            C_INSULA_DISPLACEMENT_BOX VARCHAR(20),
            C_OVERHEAT_SURROUNDING VARCHAR(20),
            C_OVERHEAT_CONDUCTORS VARCHAR(20),
			CONSTRAINT PK_ISOLATION_CURRENT_ID PRIMARY KEY(ISOLATION_CURRENT_ID),
			CONSTRAINT FK_ISOLATION_IPAO_INSPECTION_ID  FOREIGN KEY (IPAO_INSPECTION_ID) REFERENCES ipao_inspection_table(IPAO_INSPECTION_ID) ON DELETE CASCADE

);

CREATE TABLE periodic_comments_table(

		   COMMENTS_ID INT AUTO_INCREMENT,
		   PERIODIC_INSPECTION_ID INT,
		   VIEWER_USERNAME VARCHAR(225),
		   INSPECTOR_USERNAME VARCHAR(225),
		   VIEWER_EMAIL VARCHAR(225),
		   INSPECTOR_EMAIL VARCHAR(225),
		   SITE_NAME VARCHAR(225),
		   VIEWER_COMMENT VARCHAR(500),
		   VIEWER_UPDATEDATE VARCHAR(225),
		   INSPECTOR_COMMENT VARCHAR(500),
           INSPECTOR_UPDATEDATE VARCHAR(225),		
           COMMENT_APPROVE_OR_REJECT VARCHAR(225),
           VIEWER_FLAG VARCHAR(225),
           INSPECTOR_FLAG VARCHAR(225),
           NO_OF_COMMENT INT,
		   CONSTRAINT PK_COMMENTS_ID PRIMARY KEY(COMMENTS_ID),
           CONSTRAINT FK_COMMENTS_PERIODIC_INSPECTION_ID  FOREIGN KEY (PERIODIC_INSPECTION_ID) REFERENCES periodic_inspection_table(PERIODIC_INSPECTION_ID) ON DELETE CASCADE

);

CREATE TABLE inspection_outer_observation_table(

		   INSPECTION_OUTER_OBSERVATION_ID INT AUTO_INCREMENT,
		   IPAO_INSPECTION_ID INT,
		   OBSERVATION_COMPONENT_DETAILS VARCHAR(225),
		   OBSERVATION_DESCRIPTION VARCHAR(500),
		   INSPECTION_OUTER_OBSERVATION_STATUS VARCHAR(225),
		   CONSTRAINT PK_INSPECTION_OUTER_OBSERVATION_ID PRIMARY KEY(INSPECTION_OUTER_OBSERVATION_ID),
		   CONSTRAINT FK_OUTER_IPAO_INSPECTION_ID  FOREIGN KEY (IPAO_INSPECTION_ID) REFERENCES ipao_inspection_table(IPAO_INSPECTION_ID) ON DELETE CASCADE

);

CREATE TABLE inspection_inner_observation_table(

		   INSPECTION_INNER_OBSERVATIONS_ID INT AUTO_INCREMENT,
		   INSPECTION_OUTER_OBSERVATION_ID INT,
		   OBSERVATION_COMPONENT_DETAILS VARCHAR(225),
		   OBSERVATION_DESCRIPTION VARCHAR(500),
		   INSPECTION_INNER_OBSERVATION_STATUS VARCHAR(225),
		   CONSTRAINT PK_INSPECTION_OBSERVATIONS_ID PRIMARY KEY(INSPECTION_INNER_OBSERVATIONS_ID),
           CONSTRAINT FK_INSPECTION_OUTER_OBSERVATION_ID  FOREIGN KEY (INSPECTION_OUTER_OBSERVATION_ID) REFERENCES inspection_outer_observation_table(INSPECTION_OUTER_OBSERVATION_ID) ON DELETE CASCADE

);

--------> Part_4 TestingAPI

CREATE TABLE testing_reports_table (
				TESTING_REPORT_ID INT AUTO_INCREMENT,
				SITE_ID INT,
				USER_NAME VARCHAR(225),       
				CREATED_BY VARCHAR(255),
			    CREATED_DATE datetime,
			    UPDATED_BY VARCHAR(255),
	            UPDATED_DATE datetime,
				CONSTRAINT PK_TESTING_REPORT_ID PRIMARY KEY(TESTING_REPORT_ID)
              
);


CREATE TABLE testing_table (

				TESTING_ID INT AUTO_INCREMENT,
				TESTING_REPORT_ID INT,
				LOCATION_NUMBER INT,
                LOCATION_NAME VARCHAR(225),
 				TEST_ENGINEER_NAME VARCHAR(225),
 				TESTING_STATUS VARCHAR(225),
 				LOCATION_COUNT INT NOT NULL,
 				DESIGNATION VARCHAR(225),
                COMPANY_NAME VARCHAR(225),
				DATE VARCHAR(225),
 				CONSTRAINT PK_TESTING_ID PRIMARY KEY(TESTING_ID),
				CONSTRAINT FK_DISTRIBUTION_TESTING_REPORT_ID FOREIGN KEY (TESTING_REPORT_ID) REFERENCES testing_reports_table(TESTING_REPORT_ID) ON DELETE CASCADE 
               
);

CREATE TABLE test_dist_records_table (
				TEST_DIST_RECORD_ID INT AUTO_INCREMENT,
				TESTING_ID INT,
				TEST_DIST_RECORDS_STATUS VARCHAR(20),
				LOCATION_COUNT INT NOT NULL,
				CONSTRAINT PK_TEST_DIST_RECORD_ID PRIMARY KEY(TEST_DIST_RECORD_ID),
				CONSTRAINT FK_TEST_DIST_RECORD_TESTING_ID FOREIGN KEY (TESTING_ID) REFERENCES testing_table(TESTING_ID) ON DELETE CASCADE     

)

CREATE TABLE testing_distribution_table (

                DISTRIBUTION_ID INT AUTO_INCREMENT,
				TEST_DIST_RECORD_ID INT,
                DISTRIBUTION_BOARD_DETAILS VARCHAR(225),
				REFERANCE VARCHAR(225),
				LOCATION VARCHAR(225),
				CORRECT_SUPPLY_POLARITY VARCHAR(225),
				NUM_OUTPUT_CIRCUITS_USE VARCHAR(225),
				RATINGS_AMPS VARCHAR(225),
				NUM_OUTPUT_CIRCUITS_SPARE VARCHAR(225),
				INSTALLED_EQUIPMENT_VULNARABLE  VARCHAR(225),
				SOURCE_FROM_SUPPLY VARCHAR(225),
				INCOMING_FAULTCURRENT VARCHAR(225),
				INCOMING_VOLTAGE VARCHAR(225),
				INCOMING_LOOPIMPEDANCE VARCHAR(225),
				CONSTRAINT PK_TESTING_DISTRIBUTION_ID PRIMARY KEY(DISTRIBUTION_ID),
				CONSTRAINT FK_DISTRIBUTION_TEST_DIST_RECORD_ID FOREIGN KEY (TEST_DIST_RECORD_ID) REFERENCES test_dist_records_table(TEST_DIST_RECORD_ID) ON DELETE CASCADE     

				
	);
	
CREATE TABLE testing_incoming_distribution_table (

                INCOMING_DISTRIBUTION_ID INT AUTO_INCREMENT,
				TESTING_REPORT_ID INT,
				INCOMING_VOLTAGE VARCHAR(225),
				INCOMING_LOOP_IMPEDANCE VARCHAR(225),
				INCOMING_FAULTCURRENT VARCHAR(225),
				SOURCE_FROM_SUPPLY VARCHAR(225),
				INCOMING_ACTUALLOAD VARCHAR(225),
				CONSTRAINT PK_INCOMING_ID PRIMARY KEY(INCOMING_DISTRIBUTION_ID),
				CONSTRAINT FK_TESTING_REPORT_ID FOREIGN KEY (TESTING_REPORT_ID) REFERENCES testing_reports_table(TESTING_REPORT_ID) ON DELETE CASCADE     

				
	);

CREATE TABLE testing_records_table ( 
                TESTING_RECORD_ID INT AUTO_INCREMENT,
				TEST_DIST_RECORD_ID INT,
 				CIRCUIT_NO VARCHAR(225),
				CIRCUIT_DESC  VARCHAR(225),
				CIRCUIT_STANDARD_NO  VARCHAR(225),
				CIRCUIT_MAKE VARCHAR(225),
				CIRCUIT_TYPE  VARCHAR(225), 
				CIRCUIT_CURRENT_CURVE VARCHAR(225), 
				CIRCUIT_NUMBER_OF_POLES  VARCHAR(225),
				CIRCUIT_RATING VARCHAR(225), 
				CIRCUIT_BREAKING_CAPACITY VARCHAR(225),
                INSULATION_RESISTANCE VARCHAR(225),
				SHORT_CIRCUIT_SETTING VARCHAR(225),
				E_F_SETTING VARCHAR(225),
				CONDUCTOR_INSTALLATION VARCHAR(225),
				CONDUCTOR_PHASE VARCHAR(225),
				CONDUCTOR_NEUTRAL VARCHAR(225),
				CONDUCTOR_PECPC VARCHAR(225),
				CONTINUTIY_APPROXIMATELENGTH VARCHAR(225),
				CONTINUTIY_R1_R2 VARCHAR(225),
				CONTINUTIY_R2 VARCHAR(225),
				MAX_ALLOWED_VALUE VARCHAR(225),
				CONTINUITY_REMARKS VARCHAR(225),
				CONTINUTIY_POLARITY VARCHAR(225),
				TEST_VOLTAGE VARCHAR(225),
				TEST_LOOPIMPEDANCE VARCHAR(225),
				TEST_FAULTCURRENT VARCHAR(225),
				DISCONNECTION_TIME VARCHAR(225),
				 
				RCD_CURRENT VARCHAR(225),
				RCD_OPERATINGCURRENT VARCHAR(225),
				RCD_OPERATINGFIVECURRENT VARCHAR(225),
				RCD_TESTBUTTONOPERATION VARCHAR(225),
				RCD_REMARKS VARCHAR(225),

				TESTING_RECORD_STATUS VARCHAR(225),
				RCD_TYPE VARCHAR(225),

					
				CONSTRAINT PK_TESTING_RECORD_ID PRIMARY KEY(TESTING_RECORD_ID),
				CONSTRAINT FK_TESTING_RECORD_TEST_DIST_RECORD_ID FOREIGN KEY (TEST_DIST_RECORD_ID) REFERENCES test_dist_records_table(TEST_DIST_RECORD_ID) ON DELETE CASCADE     

 );
 
CREATE TABLE testing_records_sourcesupply (

                SOURCESUPPLY_ID INT AUTO_INCREMENT,
				TESTING_RECORD_ID INT,
				TEST_VOLTAGE VARCHAR(225),
				TEST_LOOPIMPEDANCE VARCHAR(225),
				TEST_FAULTCURRENT VARCHAR(225),
				DISCONNECTION_TIME VARCHAR(225),
				CONSTRAINT PK_SOURCESUPPLY_ID PRIMARY KEY(SOURCESUPPLY_ID),
				CONSTRAINT FK_SOURCESUPPLY_TESTING_RECORD_ID FOREIGN KEY (TESTING_RECORD_ID) REFERENCES testing_records_table(TESTING_RECORD_ID) ON DELETE CASCADE     
				
	);
 
 CREATE TABLE testing_comments_table(

		   COMMENTS_ID INT AUTO_INCREMENT,
		   TESTING_REPORT_ID INT,
		   VIEWER_USERNAME VARCHAR(225),
		   INSPECTOR_USERNAME VARCHAR(225),
		   VIEWER_EMAIL VARCHAR(225),
		   INSPECTOR_EMAIL VARCHAR(225),
		   SITE_NAME VARCHAR(225),
		   VIEWER_COMMENT VARCHAR(500),
		   VIEWER_UPDATEDATE VARCHAR(225),
		   INSPECTOR_COMMENT VARCHAR(500),
           INSPECTOR_UPDATEDATE VARCHAR(225),		
           COMMENT_APPROVE_OR_REJECT VARCHAR(225),
           VIEWER_FLAG VARCHAR(225),
           INSPECTOR_FLAG VARCHAR(225),
           NO_OF_COMMENT INT,
		   CONSTRAINT PK_COMMENTS_ID PRIMARY KEY(COMMENTS_ID),
		   CONSTRAINT FK_COMMENTS_TESTING_REPORT_ID FOREIGN KEY (TESTING_REPORT_ID) REFERENCES testing_reports_table(TESTING_REPORT_ID) ON DELETE CASCADE 

);


CREATE TABLE testing_equipment_table(
		   
		   EQUIPMENT_ID INT AUTO_INCREMENT,
		   TESTING_ID INT,
		   EQUIPMENT_NAME VARCHAR(255),
		   EQUIPMENT_MAKE VARCHAR(255),
		   EQUIPMENT_MODEL VARCHAR(255),
		   EQUIPMENT_SERIAL_NO VARCHAR(255),
		   EQUIPMENT_CALIBRATION_DUE_DATE DATETIME,
		   TESTING_EQUIPMENT_STATUS VARCHAR(255),
		   CONSTRAINT PK_EQUIPMENT_ID PRIMARY KEY(EQUIPMENT_ID),
		   CONSTRAINT FK_EQUIPMENT_TESTING_ID FOREIGN KEY (TESTING_ID) REFERENCES testing_table(TESTING_ID) ON DELETE CASCADE
);

CREATE TABLE testing_inner_observations_table(

		   TESTING_INNER_OBSERVATIONS_ID INT AUTO_INCREMENT,
		   TEST_DIST_RECORD_ID INT,
		   OBSERVATION_COMPONENT_DETAILS VARCHAR(225),
		   OBSERVATION_DESCRIPTION VARCHAR(500),
		   TESTING_INNER_OBSERVATION_STATUS VARCHAR(225),
		   CONSTRAINT PK_TESTING_INNER_OBSERVATIONS_ID PRIMARY KEY(TESTING_INNER_OBSERVATIONS_ID),
           CONSTRAINT FK_INNER_TEST_DIST_RECORD_ID FOREIGN KEY (TEST_DIST_RECORD_ID) REFERENCES test_dist_records_table(TEST_DIST_RECORD_ID) ON DELETE CASCADE

);

--------> Part_5 Summary_Section

 CREATE TABLE summary_table (
            SUMMARY_ID INT AUTO_INCREMENT,
			SITE_ID INT,
			USER_NAME VARCHAR(255),
            LIMITATIONS_INSPECTION  VARCHAR(255),
            EXTENT_INSTALLATION VARCHAR(255),
            AGREED_LIMITATIONS  VARCHAR(255),
            AGREED_WITH VARCHAR(255),
            OPERATIONAL_LIMITATIONS VARCHAR(255),
            INSPECTION_TESTING_DETAILED VARCHAR(255),
            INSPECTION_REPORT_TESTRESULT VARCHAR(255),
            RECOMMENDATIONS_DATE VARCHAR(255),
            GENERAL_CONDITION_INSTALLATION VARCHAR(500),
            OVERALL_ASSESSMENT_INSTALLATION VARCHAR(255),
            CREATED_BY VARCHAR(255),
		    CREATED_DATE datetime,
		    UPDATED_BY VARCHAR(255),
            UPDATED_DATE datetime,
            CONSTRAINT PK_SUMMARY_ID PRIMARY KEY(SUMMARY_ID)
              
);

CREATE TABLE declaration_table (
            DECLARATION_ID INT AUTO_INCREMENT,
			SUMMARY_ID INT,
            DECLARATION_ROLE  VARCHAR(255),
            NAME VARCHAR(255),
            SIGNATURE  LONGTEXT,
            COMPANY VARCHAR(255),
            POSITION VARCHAR(255),
            ADDRESS VARCHAR(500),
            DATE VARCHAR(255),			
            CONSTRAINT PK_DECLARATION_ID PRIMARY KEY(DECLARATION_ID),
			CONSTRAINT FK_DECLARATION_SUMMARY_ID FOREIGN KEY (SUMMARY_ID) REFERENCES summary_table(SUMMARY_ID) ON DELETE CASCADE              
);


 CREATE TABLE summary_comments_table(

		   COMMENTS_ID INT AUTO_INCREMENT,
		   SUMMARY_ID INT,
		   VIEWER_USERNAME VARCHAR(225),
		   INSPECTOR_USERNAME VARCHAR(225),
		   VIEWER_EMAIL VARCHAR(225),
		   INSPECTOR_EMAIL VARCHAR(225),
		   SITE_NAME VARCHAR(225),
		   VIEWER_COMMENT VARCHAR(500),
		   VIEWER_UPDATEDATE VARCHAR(225),
		   INSPECTOR_COMMENT VARCHAR(500),
           INSPECTOR_UPDATEDATE VARCHAR(225),		
           COMMENT_APPROVE_OR_REJECT VARCHAR(225),
           VIEWER_FLAG VARCHAR(225),
           INSPECTOR_FLAG VARCHAR(225),
           NO_OF_COMMENT INT,
		   CONSTRAINT PK_COMMENTS_ID PRIMARY KEY(COMMENTS_ID),
		   CONSTRAINT FK_COMMENTS_SUMMARY_ID FOREIGN KEY (SUMMARY_ID) REFERENCES summary_table(SUMMARY_ID) ON DELETE CASCADE              

);

CREATE TABLE summary_observations_table (
            OBSERVATIONS_ID INT AUTO_INCREMENT,
			SUMMARY_ID INT,
			REFERENCE_ID INT,
            FURTHER_ACTIONS  VARCHAR(255),
            COMMENT VARCHAR(255),
            OBSERVATIONS VARCHAR(500),
            OBERVATION_STATUS VARCHAR(20),
            OBSERVATION_COMPONENT_DETAILS VARCHAR(225),
            CONSTRAINT PK_OBSERVATIONS_ID PRIMARY KEY(OBSERVATIONS_ID),
			CONSTRAINT FK_SUMMARY_OBSERVATIONS_ID FOREIGN KEY (SUMMARY_ID) REFERENCES summary_table(SUMMARY_ID) ON DELETE CASCADE              
);

CREATE TABLE summary_inner_observations_table (
            INNER_OBSERVATIONS_ID INT AUTO_INCREMENT,
			OBSERVATIONS_ID INT,
			REFERENCE_ID INT,
            FURTHER_ACTIONS  VARCHAR(255),
            COMMENT VARCHAR(255),
            OBSERVATIONS VARCHAR(500),
            OBERVATION_STATUS VARCHAR(20),
            OBSERVATION_COMPONENT_DETAILS VARCHAR(225),
            CONSTRAINT PK_INNER_OBSERVATIONS_ID PRIMARY KEY(INNER_OBSERVATIONS_ID),
			CONSTRAINT FK_INNER_OBSERVATIONS_ID FOREIGN KEY (OBSERVATIONS_ID) REFERENCES summary_observations_table(OBSERVATIONS_ID) ON DELETE CASCADE              
);


	
	
	CREATE TABLE application_license(
					APPLICATION_LICENSEID  INT AUTO_INCREMENT,
					NO_OF_LICENSE INT,
					INSPECTOR_NAME VARCHAR(255),
					INSPECTOR_EMAIL VARCHAR(255),
					PHONE_NUM VARCHAR(255),
					STATUS VARCHAR(255),
					APPLICATION_NAME VARCHAR(255),
 					LICENSE_AMOUNT VARCHAR(255),
					ORDERID VARCHAR(255),
					CREATED_DATE datetime,
					UPDATED_DATE datetime,
					CREATED_BY VARCHAR(255),
					UPDATED_BY VARCHAR(255),
				 
					CONSTRAINT PK_APPLICATION_LICENSEID PRIMARY KEY(APPLICATION_LICENSEID)
	);

	